### ISSUE TITLE
User Stories: Interest Epic Story 5

### ISSUE THREAD

**Issue by juliasklodowska** [juliasklodowska/is218003final#70]
**User Story**

As Emma scrolls, as a user, she would love to see what enticing stuff the website has to offer.

**Acceptance Criteria**

- [x] add 4 card components as menu items 
- [x] title this section "Community Favorites" with a button to see the full menu: "Full Menu"
- [x]  title the drinks warm and fun names like: Nurture Nut Latte, Garden Hug Matcha, Compassion Cappuccino, and Meadow Mint Mocha on the home page, accompanied by prices next to them and a photo of the drink above the name

**Result**

A menu on a homepage of a website that offers warm, cozy, welcome drinks with cute names.
