### ISSUE TITLE
User Stories: Interest Epic Story 6

### ISSUE THREAD

**Issue by juliasklodowska** [juliasklodowska/is218003final#71]
**User Story**

As a user, Emma hopes to gain more information about this rewards program stated in the hero section. 

**Acceptance Criteria**

- [x] add a section with a photo of happy customers (liking)
- [x] title this section "Become Part of Our Family" with text explaining the rewards program: "Join our rewards program today and receive a free drink on your next order. Hurry, this cozy welcome gift expires in just 7 days from sign-up. Start your journey to comfort now!" (which states reciprocity and scarcity)
- [x] add a "Join our Family" button to join the rewards program

**Result**

A section in home page that describes more about rewards program and entices user to join it more through persuasion of happy faces and reciprocity + scarcity.
