### ISSUE TITLE
User Stories: Interest Epic Story 8

### ISSUE THREAD

**Issue by juliasklodowska** [juliasklodowska/is218003final#73]
**User Story**

Emma, as a user, wants to see a section that adheres to her love for community service. 

**Acceptance Criteria**

- [x] add a community section titled "Nurturing the Community" with a photo of workers at the coffee shop, and they all look welcome, warm, and happy and are doing some sort of community service. 
- [x] add description talking about how they help out the community apart from themselves: "At Cottage Comfort Café, we're committed to fostering meaningful initiatives that directly support and uplift the people in our community, reflecting the love and care we’ve received from every smiling face that walks through our doors." 
- [x] add "Learn More" Button for more information 

**Result**

A website that really cares about giving back to the community, but also adheres the caregiver archetype and portrays the persuasion tactic of liking.
