### ISSUE TITLE
User Stories: Interest Epic Story 10

### ISSUE THREAD

**Issue by juliasklodowska** [juliasklodowska/is218003final#75]
**User Story**

As a user, Emma wants to see a footer and see how she can contact the website if she needs anything or has questions about community service or the rewards program. 

**Acceptance Criteria**

- [x] add footer with title "Cottage Comfort Cafe" and links to Home, Community, Hours and Location, Full Menu, and Join Our Family pages
- [x] add links to the coffee shop's email, phone, Instagram, and Twitter
- [x] add link to the privacy policy page and copyright information

**Result**

A footer on a website with all important information and links needed, as well as contact information.
