### ISSUE TITLE
User Stories: Action Epic Story 3

### ISSUE THREAD

**Issue by juliasklodowska** [juliasklodowska/is218003final#79]
**User Story**

Emma wants to see the menu. 

**Acceptance Criteria**

- [x] in navigation menu, make link to menu page
- [x] in hero section "See Menu" button, add link to menu page
- [x] in menu on homepage, also add link
- [x] add link to menu in footer
- [x] create menu page with "Regular Menu" title, the regular menu shown, and then title for "Specialty Drinks" and 8 cards showing the 8 drinks (with photos and prices)

**Result**

User gets sent to menu page and has a menu page where they see more information about the menu and more drinks.
