### ISSUE TITLE
User Stories: Action Epic 4

### ISSUE THREAD

**Issue by juliasklodowska** [juliasklodowska/is218003final#80]
**User Story**

Emma wants to join the rewards program. 

**Acceptance Criteria**

- [x] both "Join our Family" buttons on home page work and in footer
- [x] "Join Now" button works in navbar
- [x] make a join our family page with title "Join Our Family" that allows her to enter her email address and name (and accept terms and conditions) to get into the rewards program. This section also states: "Join our rewards program and enjoy a free coffee within a week! Plus, every 10th visit rewards you with a free drink, and you get 50% off for sharing your love on social media" and has a "Join Now" button for submission.

**Result**

A website with a rewards program that people can join.
