### ISSUE TITLE
User Stories: Action Epic 7

### ISSUE THREAD

**Issue by juliasklodowska** [juliasklodowska/is218003final#83]
**User Story**

Emma wants to learn more about the community, since helping people out is one of her many caregiver traits.

**Acceptance Criteria**

- [x] add a link to community page from "Learn More" link on home page, as well as links in navigation bar and footer
- [x] create or design Community page with title "Giving Back to the Community" and a description stating: "Cottage Comfort Café pulses with community spirit. Join us monthly for 'Caring Cup Day'—our hosted day of charity, donations, or community service. Together, we make a difference—one cup, one cause, one community at a time." 
- [x] add 2 cards in community page describing "Food Drive Donations" and "Gardening" events, and how people can help out by emailing or calling the coffee shop. These cards also have photos of the events.

**Result**

A website with a community page with community service events.
